# Generated by Django 5.0.6 on 2024-07-21 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_catergory_category_remove_product_catergory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
    ]
