# Generated by Django 5.0.6 on 2024-07-22 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_review_customer_review_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='customer',
        ),
    ]
